### ISSUE TITLE
Failed to build it on latest archlinux

### ISSUE THREAD

**Issue by STRRL** [chaos-mesh/chaos-driver#1]
I setup a vm with latest archlinux. When try to install chaos driver with `yay`, it tells me:

```
[strrl@archlinux chaos-driver]$ yay chaos-driver-dkms
1 aur/chaos-driver-dkms 0.1.1-2 (+0 0.00) (Installed: 0.1.1-1)
    A kernel module to inject error or latency inside the linux kernel
==> Packages to install (eg: 1 2 3, 1-3 or ^4)
==> 1
:: Checking for conflicts...
:: Checking for inner conflicts...
[Aur:1]  chaos-driver-0.1.1-2 (chaos-driver-dkms)

  1 chaos-driver (chaos-driver-dkms)         (Installed) (Build Files Exist)
==> Packages to cleanBuild?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> 
:: PKGBUILD up to date, Skipping (1/0): chaos-driver
  1 chaos-driver (chaos-driver-dkms)         (Installed) (Build Files Exist)
==> Diffs to show?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> 
:: (1/1) Parsing SRCINFO: chaos-driver (chaos-driver-dkms)

==> Making package: chaos-driver 0.1.1-1 (Thu 21 Apr 2022 10:16:06 PM CST)
==> Retrieving sources...
  -> Found v0.1.1.tar.gz
==> Validating source files with sha256sums...
    v0.1.1.tar.gz ... Passed
==> Making package: chaos-driver 0.1.1-1 (Thu 21 Apr 2022 10:16:08 PM CST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found v0.1.1.tar.gz
==> Validating source files with sha256sums...
    v0.1.1.tar.gz ... Passed
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Extracting v0.1.1.tar.gz with bsdtar
==> Starting prepare()...
==> Sources are ready.
==> Making package: chaos-driver 0.1.1-1 (Thu 21 Apr 2022 10:16:12 PM CST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> WARNING: Using existing $srcdir/ tree
==> Sources are ready.
 -> chaos-driver-0.1.1-1 already made -- skipping build
loading packages...
warning: chaos-driver-dkms-0.1.1-1 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Packages (1) chaos-driver-dkms-0.1.1-1

Total Installed Size:  0.06 MiB
Net Upgrade Size:      0.00 MiB

:: Proceed with installation? [Y/n] 
(1/1) checking keys in keyring                                                                                                                                                                [#######################################################################################################################] 100%
(1/1) checking package integrity                                                                                                                                                              [#######################################################################################################################] 100%
(1/1) loading package files                                                                                                                                                                   [#######################################################################################################################] 100%
(1/1) checking for file conflicts                                                                                                                                                             [#######################################################################################################################] 100%
(1/1) checking available disk space                                                                                                                                                           [#######################################################################################################################] 100%
:: Running pre-transaction hooks...
(1/1) Remove upgraded DKMS modules
==> dkms remove chaos-driver/0.1.1
:: Processing package changes...
(1/1) reinstalling chaos-driver-dkms                                                                                                                                                          [#######################################################################################################################] 100%
:: Running post-transaction hooks...
(1/2) Arming ConditionNeedsUpdate...
(2/2) Install DKMS modules
==> dkms install --no-depmod chaos-driver/0.1.1 -k 5.17.3-arch1-1
Error! Bad return status for module build on kernel: 5.17.3-arch1-1 (x86_64)
Consult /var/lib/dkms/chaos-driver/0.1.1/build/make.log for more information.
==> WARNING: `dkms install --no-depmod chaos-driver/0.1.1 -k 5.17.3-arch1-1' exited 10
[strrl@archlinux chaos-driver]$ 
```

```
[strrl@archlinux chaos-driver]$ cat /var/lib/dkms/chaos-driver/0.1.1/build/make.log
DKMS make.log for chaos-driver-0.1.1 for kernel 5.17.3-arch1-1 (x86_64)
Thu Apr 21 10:16:12 PM CST 2022
make -C /lib/modules/5.17.3-arch1-1/build M=/var/lib/dkms/chaos-driver/0.1.1/build modules
make[1]: Entering directory '/usr/lib/modules/5.17.3-arch1-1/build'
  CC [M]  /var/lib/dkms/chaos-driver/0.1.1/build/injection.o
  CC [M]  /var/lib/dkms/chaos-driver/0.1.1/build/main.o
  CC [M]  /var/lib/dkms/chaos-driver/0.1.1/build/chaos_device.o
  CC [M]  /var/lib/dkms/chaos-driver/0.1.1/build/ioem.o
In file included from /var/lib/dkms/chaos-driver/0.1.1/build/injection.h:1,
                 from /var/lib/dkms/chaos-driver/0.1.1/build/injection.c:7:
/var/lib/dkms/chaos-driver/0.1.1/build/protocol.h:3:10: fatal error: stddef.h: No such file or directory
    3 | #include <stddef.h>
      |          ^~~~~~~~~~
compilation terminated.
make[2]: *** [scripts/Makefile.build:288: /var/lib/dkms/chaos-driver/0.1.1/build/injection.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /var/lib/dkms/chaos-driver/0.1.1/build/chaos_device.c:8:
/var/lib/dkms/chaos-driver/0.1.1/build/protocol.h:3:10: fatal error: stddef.h: No such file or directory
    3 | #include <stddef.h>
      |          ^~~~~~~~~~
compilation terminated.
make[2]: *** [scripts/Makefile.build:288: /var/lib/dkms/chaos-driver/0.1.1/build/chaos_device.o] Error 1
/var/lib/dkms/chaos-driver/0.1.1/build/main.c:27:10: fatal error: linux/elevator.h: No such file or directory
   27 | #include <linux/elevator.h>
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [scripts/Makefile.build:288: /var/lib/dkms/chaos-driver/0.1.1/build/main.o] Error 1
/var/lib/dkms/chaos-driver/0.1.1/build/ioem.c:7:10: fatal error: linux/elevator.h: No such file or directory
    7 | #include <linux/elevator.h>
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [scripts/Makefile.build:288: /var/lib/dkms/chaos-driver/0.1.1/build/ioem.o] Error 1
make[1]: *** [Makefile:1831: /var/lib/dkms/chaos-driver/0.1.1/build] Error 2
make[1]: Leaving directory '/usr/lib/modules/5.17.3-arch1-1/build'
make: *** [Makefile:11: all] Error 2

```

**Comment by YangKeao** [comment]
In Linux 5.16, someone moves the public `elevator.h` to an internal private directory, and this repo cannot compile. Maybe I should hurry up to submit the related patch to the kernel mainline (but I'm not sure whether it will be accepted).

**Comment by STRRL** [comment]
I got that. I would use an earlier kernel to try it.
